name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org9a90568c.crm7.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://org77d9328e.crm7.dynamics.com/
      CLIENT_ID: 461aaff2-7a35-4d55-987b-9590c1377870
      TENANT_ID: f45d97e7-6d68-497b-8ff3-dc640d3317a1    
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
